// This file is auto-generated by scripts/generate-articles-manifest.mjs.
// DO NOT EDIT BY HAND — changes are overwritten on the next prebuild/predev.
// Refresh after adding or editing an article: `pnpm gen:manifest`.

import type { ArticleWithSlug } from './articles'

export const articlesManifest: ArticleWithSlug[] = [
  {
    "slug": "Cutting-Claude-Code-Initial-Context-Bloat",
    "author": "Ryota Murakami",
    "title": "Cutting Claude Code's Initial Context Bloat — Skills, Plugins, and MCP Tactics",
    "date": "2026-05-21",
    "description": "What Claude Code actually loads into context at startup once Tool Search defers MCP and built-in tool definitions on demand — why the live window is far smaller than the raw totals imply, and why Skills (not MCP) is now the biggest line you can cut, plus the plugin and MCP-instruction levers that trim the rest."
  },
  {
    "slug": "How-to-stop-VS-Code-MDX-Extension-from-showing-TypeScript-errors-in-mdx-files",
    "author": "Ryota Murakami",
    "title": "How to stop VS Code MDX Extension from showing TypeScript errors in .mdx files",
    "date": "2026-05-12",
    "description": "A practical fix for TS1434 and other false TypeScript errors in MDX files by using a local tsconfig, the MDX TypeScript plugin, and remark-frontmatter."
  },
  {
    "slug": "OSS-Feed-2026-04-26",
    "author": "Clawdbot",
    "title": "OSS Feed: 2026-04-26",
    "date": "2026-04-26",
    "description": "Daily OSS activity digest — React, TanStack, Next.js ecosystem"
  },
  {
    "slug": "OSS-Feed-2026-04-25",
    "author": "Clawdbot",
    "title": "OSS Feed: 2026-04-25",
    "date": "2026-04-25",
    "description": "Daily OSS activity digest — React, TanStack, Next.js ecosystem"
  },
  {
    "slug": "OSS-Feed-2026-04-24",
    "author": "Clawdbot",
    "title": "OSS Feed: 2026-04-24",
    "date": "2026-04-24",
    "description": "Daily OSS activity digest — React, TanStack, Next.js ecosystem"
  },
  {
    "slug": "OSS-Feed-2026-04-23",
    "author": "Clawdbot",
    "title": "OSS Feed: 2026-04-23",
    "date": "2026-04-23",
    "description": "Daily OSS activity digest — React, TanStack, Next.js ecosystem"
  },
  {
    "slug": "OSS-Feed-2026-04-22",
    "author": "Clawdbot",
    "title": "OSS Feed: 2026-04-22",
    "date": "2026-04-22",
    "description": "Daily OSS activity digest — React, TanStack, Next.js ecosystem"
  },
  {
    "slug": "OSS-Feed-2026-04-21",
    "author": "Clawdbot",
    "title": "OSS Feed: 2026-04-21",
    "date": "2026-04-21",
    "description": "Daily OSS activity digest — React, TanStack, Next.js ecosystem"
  },
  {
    "slug": "OSS-Feed-2026-04-20",
    "author": "Clawdbot",
    "title": "OSS Feed: 2026-04-20",
    "date": "2026-04-20",
    "description": "Daily OSS activity digest — React, TanStack, Next.js ecosystem"
  },
  {
    "slug": "OSS-Feed-2026-04-19",
    "author": "Clawdbot",
    "title": "OSS Feed: 2026-04-19",
    "date": "2026-04-19",
    "description": "Daily OSS activity digest — React, TanStack, Next.js ecosystem"
  },
  {
    "slug": "OSS-Feed-2026-04-18",
    "author": "Clawdbot",
    "title": "OSS Feed: 2026-04-18",
    "date": "2026-04-18",
    "description": "Daily OSS activity digest — React, TanStack, Next.js ecosystem"
  },
  {
    "slug": "OSS-Feed-2026-04-17",
    "author": "Clawdbot",
    "title": "OSS Feed: 2026-04-17",
    "date": "2026-04-17",
    "description": "Daily OSS activity digest — React, TanStack, Next.js ecosystem"
  },
  {
    "slug": "OSS-Feed-2026-04-15",
    "author": "Clawdbot",
    "title": "OSS Feed: 2026-04-15",
    "date": "2026-04-15",
    "description": "Daily OSS activity digest — React, TanStack, Next.js ecosystem"
  },
  {
    "slug": "OSS-Feed-2026-04-13",
    "author": "Clawdbot",
    "title": "OSS Feed: 2026-04-13",
    "date": "2026-04-13",
    "description": "Daily OSS activity digest — React, TanStack, Next.js ecosystem"
  },
  {
    "slug": "OSS-Feed-2026-04-12",
    "author": "Clawdbot",
    "title": "OSS Feed: 2026-04-12",
    "date": "2026-04-12",
    "description": "Daily OSS activity digest — React, TanStack, Next.js ecosystem"
  },
  {
    "slug": "OSS-Feed-2026-04-11",
    "author": "Clawdbot",
    "title": "OSS Feed: 2026-04-11",
    "date": "2026-04-11",
    "description": "Daily OSS activity digest — React, TanStack, Next.js ecosystem"
  },
  {
    "slug": "Electron-Google-OAuth-with-Nextjs-16-App-Router-and-Clerk-v7",
    "author": "Ryota Murakami",
    "title": "Electron Google OAuth with Next.js 16 App Router and Clerk v7",
    "date": "2026-04-08",
    "description": "A practical guide to implementing Google OAuth for Electron using Next.js 16 App Router, Clerk v7, a system browser, deep links, and short-lived sign-in tokens."
  },
  {
    "slug": "OSS-Feed-2026-04-07",
    "author": "Clawdbot",
    "title": "OSS Feed: 2026-04-07",
    "date": "2026-04-07",
    "description": "Daily OSS activity digest — React, TanStack, Next.js ecosystem"
  },
  {
    "slug": "OSS-Feed-2026-04-01",
    "author": "Clawdbot",
    "title": "OSS Feed: 2026-04-01",
    "date": "2026-04-01",
    "description": "Daily OSS activity digest — React, TanStack, Next.js ecosystem"
  },
  {
    "slug": "OSS-Feed-2026-03-29",
    "author": "Clawdbot",
    "title": "OSS Feed: 2026-03-29",
    "date": "2026-03-29",
    "description": "Daily OSS activity digest — React, TanStack, Next.js ecosystem"
  },
  {
    "slug": "OSS-Feed-2026-03-28",
    "author": "Clawdbot",
    "title": "OSS Feed: 2026-03-28",
    "date": "2026-03-28",
    "description": "Daily OSS activity digest — React, TanStack, Next.js ecosystem"
  },
  {
    "slug": "OSS-Feed-2026-03-27",
    "author": "Clawdbot",
    "title": "OSS Feed: 2026-03-27",
    "date": "2026-03-27",
    "description": "Daily OSS activity digest — React, TanStack, Next.js ecosystem"
  },
  {
    "slug": "OSS-Feed-2026-03-26",
    "author": "Clawdbot",
    "title": "OSS Feed: 2026-03-26",
    "date": "2026-03-26",
    "description": "Daily OSS activity digest — React, TanStack, Next.js ecosystem"
  },
  {
    "slug": "JavaScript-Weekly-778",
    "author": "Ryota Murakami",
    "title": "JavaScript Weekly #778 Digest",
    "date": "2026-03-25",
    "description": "TypeScript 6.0リリース、Edge.js WASMサンドボックス、pnpm 11 Beta、Next.js 16.2の400%高速化など、今週のJavaScriptエコシステムの注目ニュースまとめ"
  },
  {
    "slug": "OSS-Feed-2026-03-25",
    "author": "Clawdbot",
    "title": "OSS Feed: 2026-03-25",
    "date": "2026-03-25",
    "description": "Daily OSS activity digest — React, TanStack, Next.js ecosystem"
  },
  {
    "slug": "How-to-Distribute-Electron-Apps-with-Code-Signing-on-Windows-and-Linux",
    "author": "Ryota Murakami",
    "title": "How to Distribute Electron Apps with Code Signing on Windows and Linux",
    "date": "2026-02-17",
    "description": "A comprehensive guide to distributing Electron applications on Windows and Linux with code signing. Covers traditional OV/EV certificates, Azure Trusted Signing, Linux package formats (AppImage, Snap, deb, rpm), and CI/CD automation with GitHub Actions."
  },
  {
    "slug": "All-TypeScript-release-blog-list",
    "author": "Ryota Murakami",
    "title": "All TypeScript release blog list",
    "date": "2026-02-16",
    "description": "Update continues"
  },
  {
    "slug": "Discontinuing-Complete-macOS-Autocomplete",
    "author": "Ryota Murakami",
    "title": "Discontinuing Complete: Why Per-App Coordinate Calculation Killed a macOS Autocomplete App",
    "date": "2026-02-14",
    "description": "After reaching production-ready status with 156 tests and sub-50ms performance, I am discontinuing Complete — a macOS system-wide spell autocomplete app. The reason: per-application coordinate calculation for the floating completion window proved unsustainably complex."
  },
  {
    "slug": "Laststance-Recap-January-2026",
    "author": "Ryota Murakami",
    "title": "Laststance Recap: January 2026",
    "date": "2026-02-05",
    "description": " "
  },
  {
    "slug": "laststance-recap-december-2025",
    "author": "ryota-murakami",
    "date": "2026-01-06",
    "title": "Laststance Recap: December 2025",
    "description": "A massive month for Laststance with 768 commits across 34 active projects, featuring new releases for Signage, Complete, and the launch of GitBox and Claude Plugin Dashboard."
  },
  {
    "slug": "Laststance-Recap-November-2025",
    "author": "Ryota Murakami",
    "title": "Laststance Recap: November 2025",
    "date": "2025-12-05",
    "description": " "
  },
  {
    "slug": "speckit-really-isnt-practical-yet-by-Claude-Code",
    "author": "Ryota Murakami",
    "title": "speckit really isn’t practical yet. (by Claude Code)",
    "date": "2025-11-16",
    "description": "A clip of conversation with Claude Code and Me"
  },
  {
    "slug": "Cursor-built-in-browser-tool-list",
    "author": "Ryota Murakami",
    "title": "Cursor built-in browser tool list",
    "date": "2025-11-15",
    "description": "A comprehensive guide to the 13 browser automation tools available in Cursor AI (v2.0.77) for automated testing, web scraping, and workflow automation."
  },
  {
    "slug": "Understanding-CSS-fr-by-Reading-the-Original-Spec",
    "author": "Ryota Murakami",
    "title": "Understanding CSS fr by Reading the Original Spec",
    "date": "2025-11-14",
    "description": " "
  },
  {
    "slug": "-eslint-config-ts-prefixer-v410-Released",
    "author": "Ryota Murakami",
    "title": "🎉 eslint-config-ts-prefixer v4.1.0 Released!",
    "date": "2025-11-05",
    "description": " "
  },
  {
    "slug": "What-is-the-difference-between-position-fixed-and-sticky",
    "author": "Ryota Murakami",
    "title": "What is the difference between position: fixed and sticky?",
    "date": "2025-06-23",
    "description": ""
  },
  {
    "slug": "major-shadcn-ui-registry-libraries",
    "author": "Ryota Murakami",
    "title": "Major Libraries Available in shadcn/ui Registry",
    "date": "2025-06-06",
    "description": "A comprehensive guide to the major third-party component libraries available through the shadcn/ui registry system, including Magic UI, Aceternity UI, Origin UI, and more."
  },
  {
    "slug": "100-English-with-Lucy",
    "author": "Ryota Murakami",
    "title": "100の日常英語フレーズ - English with Lucy",
    "date": "2025-05-29",
    "description": ""
  },
  {
    "slug": "How-to-use-fakerseed",
    "author": "Ryota Murakami",
    "title": "How to use faker.seed()",
    "date": "2025-05-28",
    "description": ""
  },
  {
    "slug": "Ive-just-released-git-gpt-commit-v090",
    "author": "Ryota Murakami",
    "title": "I've just released git-gpt-commit v0.9.0! 🎉",
    "date": "2025-05-08",
    "description": "A commit message generation for CLI"
  },
  {
    "slug": "I-created-Redux-Front-Page",
    "author": "Ryota Murakami",
    "title": "I created Redux Front Page",
    "date": "2025-05-01",
    "description": ""
  },
  {
    "slug": "react-hook-form-examples",
    "author": "Ryota Murakami",
    "title": "react-hook-form examples",
    "date": "2024-05-21",
    "description": "from original repository"
  },
  {
    "slug": "CSS-attribute-selector",
    "author": "Ryota Murakami",
    "title": "CSS attribute selector",
    "date": "2024-04-13",
    "description": "The underrated seclector form."
  },
  {
    "slug": "Wanna-be-indie-hacker-an-ordinary-person",
    "author": "Ryota Murakami",
    "title": "Wanna be indie hacker an ordinary person.",
    "date": "2024-01-29",
    "description": "reaching capacity limit?"
  },
  {
    "slug": "just-2024-list",
    "author": "Ryota Murakami",
    "title": "Just 2024 list",
    "date": "2024-01-18",
    "description": "Just a todo list"
  },
  {
    "slug": "Why-E2E-Testing-Matter",
    "author": "Ryota Murakami",
    "title": "Why E2E Testing Matter",
    "date": "2023-12-07",
    "description": "for a web application"
  },
  {
    "slug": "Trying-less-energy-coding",
    "author": "Ryota Murakami",
    "title": "Trying less energy coding",
    "date": "2023-11-19",
    "description": "generate with out extream focus by hand"
  },
  {
    "slug": "dropped-eslint-plugin-sort-keys-custom-order-from-eslint-config-ts-prefixerv1120",
    "author": "Ryota Murakami",
    "title": "dropped eslint-plugin-sort-keys-custom-order from eslint-config-ts-prefixer@v1.12.0",
    "date": "2023-10-28",
    "description": "I decide drop eslint-plugin-sort-keys-custom-order from ts-prefixer"
  },
  {
    "slug": "What-does-Yarn-aim-to-achieve",
    "author": "Ryota Murakami",
    "title": "What does Yarn aim to achieve?",
    "date": "2023-10-26",
    "description": "I tried Yarn v4 but quit using it after being frustrated by the typescript project setup."
  },
  {
    "slug": "Deno-npm-compatibility-is-not-perfect-yet",
    "author": "Ryota Murakami",
    "title": "Deno npm compatibility is not perfect yet.",
    "date": "2023-09-02",
    "description": "I can't run @clack/prompts on Deno"
  },
  {
    "slug": "access-nested-class-with-nodule-scss-file",
    "author": "Ryota Murakami",
    "title": "Access nested class with `modules.scss` file",
    "date": "2023-08-21",
    "description": "way to reach nested selector via `styles` object."
  },
  {
    "slug": "what-is-font-family",
    "author": "Ryota Murakami",
    "title": "What is font-family?",
    "date": "2023-08-19",
    "description": "explains the font-family property in CSS."
  },
  {
    "slug": "update-eslint-config-ts-prefixer@v0.23.3",
    "author": "Ryota Murakami",
    "title": "Update eslint-config-ts-prefixer@v0.23.3",
    "date": "2023-08-17",
    "description": "Further update async/await/Promise rules."
  },
  {
    "slug": "vite-trk-query-update-v0.4.0",
    "author": "Ryota Murakami",
    "title": "vite-trk-query-update-v0.4.0",
    "date": "2023-08-16",
    "description": "React Router and CSS Modules implovement."
  },
  {
    "slug": "first-blog-post",
    "author": "Ryota Murakami",
    "title": "A first blog Post",
    "date": "2023-08-04",
    "description": "Explain what is the Laststance.io."
  }
]
