version: 2
updates:
  - package-ecosystem: 'npm'
    # Files stored in `app` directory
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 10
    groups:
      all-dependencies:
        patterns:
          - '*'
    target-branch: 'main'
    ignore:
      - dependency-name: 'storybook'
      - dependency-name: '@storybook/*'
