name: Malware Safe Chain
on:
  pull_request: ~
  push:
    branches:
      - main
jobs:
  malware-safe-chain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install Aikido Safe Chain
        run: npm install -g @aikidosec/safe-chain
      - name: Setup Safe Chain for CI
        run: safe-chain setup-ci
      - name: Install dependencies with Safe Chain protection
        run: pnpm install
